import{a as g,S as L,i as u}from"./assets/vendor-56bcefdc.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const b="44213256-a0da22d27c0a561a4a975a94d",w="https://pixabay.com/api/";async function f(e,o=1){const r=await g.get(`${w}`,{params:{key:b,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}});if(r.status!==200)throw new Error("Failed to fetch images");return r.data}let l;function h(e,o){const r=document.querySelector(".gallery"),i=r.clientHeight;o&&(r.innerHTML="");const t=e.map(a=>`
    <a href="${a.largeImageURL}" class="gallery-item">
      <img src="${a.webformatURL}" alt="${a.tags}" loading="lazy">
      <div class="info">
        <p><b>Likes:</b> ${a.likes}</p>
        <p><b>Views:</b> ${a.views}</p>
        <p><b>Comments:</b> ${a.comments}</p>
        <p><b>Downloads:</b> ${a.downloads}</p>
      </div>
    </a>`).join("");r.insertAdjacentHTML("beforeend",t),l?l.refresh():l=new L(".gallery a",{caption:!0,captionsData:"alt",captionDelay:250});const s=r.clientHeight;window.scrollBy({top:s-i,behavior:"smooth"})}function c(e){u.error({title:"Error",message:e,position:"topRight"})}function v(){const e=document.querySelector(".gallery");e.innerHTML=""}function m(){console.log("+"),document.querySelector(".div-loader").classList.remove("hidden")}function y(){console.log("-"),document.querySelector(".div-loader").classList.add("hidden")}function d(e){const o=document.querySelector(".load-more");e?o.classList.remove("hidden"):o.classList.add("hidden")}let n=1,p="";document.querySelector("#search-form").addEventListener("submit",async e=>{e.preventDefault();const o=e.target.elements.searchQuery.value.trim();if(!o){c("Please enter a search query");return}p=o,n=1,v(),d(!1),m();try{const r=await f(o);r.hits.length===0?c("Sorry, there are no images matching your search query. Please try again!"):(h(r.hits,!0),d(r.totalHits>n*15))}catch(r){c(r.message)}finally{y()}});document.querySelector(".load-more").addEventListener("click",async()=>{n+=1,m();try{const e=await f(p,n);h(e.hits,!1),d(e.totalHits>n*15),e.totalHits<=n*15&&u.info({title:"info",message:"We are sorry, but you`ve reached the end of search result.",position:"topRight"})}catch(e){c(e.message)}finally{y()}});
//# sourceMappingURL=commonHelpers.js.map
